name: Deploy Prod
on:
  release:
    types: [published]


jobs:
  trigger_deploy:
    name: Trigger DO Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"Authorization": "Bearer ${{ secrets.DO_TOKEN }}"}'
